default: styles/technology.scss
ArcDark: styles/arcdark.scss
Darkest: styles/darkest.scss
Eugen: styles/application.scss
SolarizedDark: styles/solarizeddark.scss
Woolly: styles/woolly.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
